### ISSUE TITLE
Problem using "-" in the string

### ISSUE THREAD

**Issue by soerenetler** [dtuggener/CharSplit#1]
Thank you a lot for this great compount splitter. It works really good. Unfortunately it does have some problems with hyphens. 

``char_split.split_compound("Kraftfahrzeug-Haftpflichtversicherung")``
returns [[1.0, 'Kraftfahrzeug-Haftpflichtversicherung', 'Haftpflichtversicherung']]

The whole word is returned in the first part of the result. Do you know how to fix this issue?
thanks in advance :)

**Comment by johnwcowan** [comment]
Break hyphenated words yourself and pass them one part at a time.

**Comment by dtuggener** [comment]
I would consider this a bug and I have fixed the issue. 
`[[1.0, 'Kraftfahrzeug', 'Haftpflichtversicherung']]` 
is now returned.
