### ISSUE TITLE
Score is not the same as presented in paper

### ISSUE THREAD

**Issue by dvrcapture** [dtuggener/CharSplit#2]
I try the same code with same compound string but the score is -0.65. Why is that so? e.g: "Autobahnraststätte" returns:
 [-0.6561174724342663, 'Autobahn', 'Raststätte'],
 [-0.719082070992539, 'Autobahnrast', 'Stätte'],
 [-2.0207606162242056, 'Auto', 'Bahnraststätte'],
 [-2.0883545770567786, 'Autobahnrasts', 'Tätte'],
 [-2.116115029842648, 'Autobahnrastst', 'Ätte'],
 [-2.1366906474820144, 'Autobahnras', 'Tstätte'],
 [-2.155172413793103, 'Autobahnra', 'Ststätte'],
 [-2.1557478368356, 'Autobahnr', 'Aststätte'],
 [-2.237077877325982, 'Aut', 'Obahnraststätte'],
 [-2.458303592671901, 'Autob', 'Ahnraststätte'],
 [-2.709178455383891, 'Autobahnraststä', 'Tte'],
 [-2.785514345696291, 'Autobah', 'Nraststätte'],
 [-3, 'Autoba', 'Hnraststätte']]

**Comment by Laubeee** [comment]
Did you train manually?
I cloned the repo and without any training
`python char_split.py Autobahnraststätte`
returned:

0.7945872450631273      Autobahn        Raststätte
-0.7143290887876655     Auto    Bahnraststätte
-1.1132332878581173     Autobahnrast    Stätte
-1.4010051533086552     Aut     Obahnraststätte
-2.3447843979244944     Autobahnrasts   Tätte
-2.4761904761904763     Autobahnra      Ststätte
-2.4761904761904763     Autobahnr       Aststätte
-2.5733333333333333     Autob   Ahnraststätte
-2.604651162790698      Autobahnras     Tstätte
-2.7142857142857144     Autobah Nraststätte
-2.730248306997743      Autobahnrastst  Ätte
-2.8033113109925973     Autobahnraststä Tte
-3.0    Autoba  Hnraststätte

**Comment by dtuggener** [comment]
Thanks Laubee!
