### ISSUE TITLE
How to filter what words to split and what not?

### ISSUE THREAD

**Issue by nicolamorawetz** [dtuggener/CharSplit#5]
This compound splitter is amazing thank you. 
The problem I have with it is that it tends to split even words that it really shouldn't, for example the word "Präsident" is split into "Prasid", "ent". 

This flaw makes it impossible for me to use in my NLP project. 

I was wondering if you had a way to filter out words to be split and words not to be split.

This would be really helpful, thank you.

**Comment by johnwcowan** [comment]
I'm preparing a wrapper that uses a German dictionary to eliminate that problem.

**Comment by dtuggener** [comment]
I also use a dictionary of known words, i.e. that should not be split. 

Another option is to look at the split scores and set a threshold, i.e. at least 0.5 or similar:
```-0.18858709641980473	Präsi	Dent
-0.20789189504713537	Präs	Ident
-1.469852196800972	Präsid	Ent
-1.4912071766230448	Prä	Sident
```
Negative scores are always an indicator that a word shouldn't be split.
